application: gaeblog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /styles
  static_dir: static/styles

- url: /scripts
  static_dir: static/scripts

- url: /images
  static_dir: static/images

- url: /admin/.*
  script: gaeblog.admin.app
  login: admin

- url: .*
  script: gaeblog.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: django
  version: "1.2"
